name = "Better MC 4 Forge (Memphis)"
author = "Memphis"
version = "1.0.0"
description = "Private modpack for us :)"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eae1406027e51f821479d9dc9a6e363905edea69127383401778c03e8c4209d"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
