name = "Better MC 4 Forge (Memphis)"
author = "Memphis"
version = "1.0.0"
description = "Private modpack for us :)"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0945b2f5a17025e271cb396f9733bd556a32794f1aed42fb584669ef690b4d86"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
