name = "Better MC 4 Forge (Memphis)"
author = "Memphis"
version = "1.0.0"
description = "Private modpack for us :)"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ed69a5e03ff0c4b0469384266e7a848db79f8187dcff4b493d7a13f53dc66b7"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
