_version = 3

[client]
	showDhOptionsButtonInMinecraftUi = false

	[client.advanced]
		[client.advanced.graphics]
			overrideVanillaGraphicsSettings = false

			[client.advanced.graphics.genericRendering]
				enableCloudRendering = false
[common]
	[common.worldGenerator]
		enableDistantGeneration = true
		distantGeneratorMode = "PRE_EXISTING_ONLY"